change again

diff --git a/.github/workflows/pmd.yml b/.github/workflows/pmd.yml
--- a/.github/workflows/pmd.yml
+++ b/.github/workflows/pmd.yml
@@ -18,26 +18,48 @@ jobs:
         with:
           fetch-depth: '0'
 
-
-      - name: Install PMD
+      - name: Run PMD Analyser
+        id: pmd-analysis
+        uses: synergy-au/pmd-analyser-action@v2
+        with:
+          pmd-version: '6.34.0'
+          file-path: './force-app/**'
+          rules-path: './pmd-ruleset.xml'
+          error-rules: 'AvoidDirectAccessTriggerMap,AvoidDmlStatementsInLoops,AvoidHardcodingId'
+          note-rules: 'ApexDoc'
+      - name: Upload results to GitHub
+        uses: github/codeql-action/upload-sarif@v1
+        with:
+          sarif_file: pmd-output.sarif
+      - name: No PMD Errors?
         run: |
+          if ${{ steps.pmd-analysis.outputs.error-found }}
+          then
+            exit 3
+          fi
 
-          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.36.0/pmd-bin-6.36.0.zip
-          unzip pmd-bin-6.36.0.zip
 
 
-      - name: Run PMD rules
-        run: |
-          pmd-bin-6.36.0/bin/run.sh pmd -d force-app/** -R pmd-ruleset.xml -failOnViolation false -f sarif > pmd-raw-output.sarif
 
-          echo "::set-output name=error-found::false"
-          while read -r rule; do
-              RULE="$(echo "$rule" | jq --raw-output '.id')"
-              if [[ $RULE && "$ERROR_RULES" == *"$RULE"* ]]; then
-                  echo "::set-output name=error-found::true"
-                  break
-              fi
-          done <<< "$(cat pmd-raw-output.sarif | jq --compact-output '.runs[] .tool .driver .rules[]')"
+      # - name: Install PMD
+      #   run: |
+
+      #     wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.36.0/pmd-bin-6.36.0.zip
+      #     unzip pmd-bin-6.36.0.zip
+
+
+      # - name: Run PMD rules
+      #   run: |
+      #     pmd-bin-6.36.0/bin/run.sh pmd -d force-app/** -R pmd-ruleset.xml -failOnViolation false -f sarif > pmd-raw-output.sarif
+
+      #     echo "::set-output name=error-found::false"
+      #     while read -r rule; do
+      #         RULE="$(echo "$rule" | jq --raw-output '.id')"
+      #         if [[ $RULE && "$ERROR_RULES" == *"$RULE"* ]]; then
+      #             echo "::set-output name=error-found::true"
+      #             break
+      #         fi
+      #     done <<< "$(cat pmd-raw-output.sarif | jq --compact-output '.runs[] .tool .driver .rules[]')"
 
 
       # - name: Run PMD Analyser
